FROM bitnami/spark:3.3.0

USER root

RUN apt-get update && apt-get install -y \
    curl nano vim \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt